name: Build and Test C++ Code on Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest  # Pastikan menjalankan di Windows

    steps:
    - uses: actions/checkout@v2

    # Install CMake menggunakan Chocolatey
    - name: Install CMake
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        refreshenv

    # Install Visual Studio Build Tools (jika belum ada)
    - name: Install Visual Studio Build Tools
      run: |
        choco install visualstudio2019-workload-vctools -y
        refreshenv

    # Build proyek menggunakan CMake
    - name: Build with CMake
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release

    # Menjalankan tes jika diperlukan
    - name: Run tests
      run: |
        ctest --output-on-failure
